volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/${USER}/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/${USER}/data/mariadb

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx-image
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ../secrets:/run/secrets:ro
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress-image
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
      - ../secrets:/run/secrets:ro
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb-image
    volumes:
      - mariadb:/var/lib/mysql
      - ../secrets:/run/secrets:ro
    env_file:
      - .env
    networks:
      - inception
    restart: always

  redis:
   container_name: redis
   build: ./requirements/bonus/redis
   image: redis-image
   depends_on:
    - wordpress
   networks:
     - inception
   restart: always

  ftp:
   container_name: ftp
   build: ./requirements/bonus/ftp
   image: ftp-image
   ports:
    - "21:21"
    - "10000-10005:10000-10005"
   depends_on:
    - wordpress
   volumes:
    - ../secrets:/run/secrets:ro
    - wordpress:/home/${FTP_USER}/ftp/files
   env_file:
    - .env
   networks:
    - inception
   restart: always
  
  adminer:
   container_name: adminer
   build: ./requirements/bonus/adminer
   image: adminer-image
   ports:
    - "8080:8080"
   depends_on:
    - mariadb
   networks:
    - inception
   restart: always
  
  website:
   container_name: website
   build: ./requirements/bonus/website
   image: website-image
   ports:
    - "80:80"
   networks:
    - inception
   restart: always

  portainer:
   container_name: portainer
   build: ./requirements/bonus/portainer
   image: portainer-image
   ports:
    - "9000:9000"
    - "9443:9443"
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/$USER/data/portainer:/data
   networks:
    - inception
   restart: always