FROM debian:bookworm

RUN apt-get update -y && apt-get install php-fpm php-mysql -y

RUN apt-get install curl -y

# COPY ./tools/script.sh /script.sh
# COPY ./tools/wp-config.php /

# ENTRYPOINT ["sh", "script.sh"]
